name: overlaunch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  bs58: ^1.0.2
  carousel_slider: ^5.1.1
  cryptocoins_icons: ^0.3.0
  flutter:
    sdk: flutter
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: ^1.4.0
  logger: ^2.6.0
  solana: ^0.31.0+1
  solana_wallet_provider: ^0.1.9
  # solana_wallet_adapter: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
